name: Automated review

on: [push]
jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm updates
        run: npm install

      - name: Run prettier check
        run: npm run check

  test: 
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: test quality
        uses: actions/checkout@v4
      # - run: npm test

  build-container:
    needs: quality-check
    runs-on: ubuntu-latest
    env: 
    # TAG_DYNAMIC: main-1234567
      TAG_DYNAMIC: ${{ github.ref_name }}-${{ github.run_id }}
      IMG_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/angular-todos-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build docker image
        run: docker build . --file ./Dockerfile --tag $IMG_NAME:$TAG_DYNAMIC --tag $IMG_NAME:latest

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: push image to Dockerhub
        run: | 
          docker push $IMG_NAME:$TAG_DYNAMIC 
          docker push $IMG_NAME:latest
      
  
  

