name: Automated review

on: [push]
jobs: 
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: npm updates
        run: npm i

      - name: Run prettier check
        run: npm run check

  test: 
    runs-on: ubuntu-latest
    needs: quality-check
      steps:
        - name: test quality
          uses: actions/checkout@v4
      # - run: npm test

# jobs: 
#   build: 
  
  

